### ISSUE TITLE
PHP-DI Error thrown because of RequestInput constructor

### ISSUE THREAD

**Issue by ScorNinja** [zhorton34/authorize-slim-4#54]
I've traced this error down to the Bootstrapper LoadDebuggingPage.php shown below (because if I comment out line 20 it will run).

    10    class LoadDebuggingPage extends Bootstrapper
    11    {
    12        public function boot()
    13        {
        ...
    19            $blade = $this->app->resolve(Blade::class);
    20            $input = ($this->app->resolve(RequestInput::class))->all();
    21            //$input = [];

RequestInput class:

    class RequestInput
    {
        protected array $meta;
        protected array $attributes;

        public function __construct($request, $route)
        {
        ...

Error Thrown: 

    Fatal error: Uncaught DI\Definition\Exception\InvalidDefinition:
        Entry "App\Support\RequestInput" cannot be resolved: Parameter $request of __construct() has no value defined or guessable
                Full definition:  Object (
                  class = App\Support\RequestInput
                  lazy = false
                  __construct(
                    $request = #UNDEFINED#
                    $route = #UNDEFINED#
                  )
                )
                in app\vendor\php-di\php-di\src\Definition\Exception\InvalidDefinition.php:19
    Stack trace:
    #0 app\vendor\php-di\php-di\src\Definition\Resolver\ObjectCreator.php(156): DI\Definition\Exception\InvalidDefinition::create(Object(DI\Definition\ObjectDefinition), 'Entry "app\\...')
    #1 app\vendor\php-di\php-di\src\Definition\Resolver\ObjectCreator.php(71): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
    #2 app\vendor\php-di\php-di\ in app\vendor\php-di\php-di\src\Definition\Exception\InvalidDefinition.php on line 19

I assume a more recent update of PHP-DI library is the cause. Assistance would be greatly appreciated.

I've tried various imports and type hints, but not sure the solution:

    use Psr\Http\Message\ServerRequestInterface as Request;
    use Slim\Routing\Route;

**Comment by dapehe94** [comment]
Hi
I have the same problem :-(

**Comment by ScorNinja** [comment]
Usually I'm able to resolve this by ensuring the class is located in the `app\Http\HttpKernel.php` file 
```
class HttpKernel extends Kernel
{
	/**
	 * Injectable Request Input Form Request Validators
	 * @var array
	 */
	public array $requests = [
		Requests\FormRequest::class,
		Requests\StoreLoginRequest::class,
		...
	];

	...
}
```

Then in the `app\Http\Controllers\Auth\LoginController.php`, inject the class into the route.
```
class LoginController
{
	public function loginPage(View $view)
	{
		return $view('auth/login-page.php');
	}
	
	public function login(Auth $auth, View $view, StoreLoginRequest $input)
	{
		if(!$input->failed()) {
			$user = $input->getData('user')
			...
		}
		...
	}
	
	...
}
```
